# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
python -m lerobot.record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
python -m lerobot.record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat

import numpy as np

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.compute_stats import auto_downsample_height_width, sample_indices
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features, write_info
from lerobot.datasets.video_packet_writer import VideoPacketBuffer
from lerobot.datasets.video_utils import VideoEncodingManager, decode_video_frames
from lerobot.policies.factory import make_policy
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
    teleavatar,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
    teleavatar,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.control_utils import (
    init_joy_listener,
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 1
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


def sample_frames_from_video(video_path: Path, episode_length: int, fps: int) -> np.ndarray:
    """
    Sample frames from a video file for stats computation.

    Args:
        video_path: Path to the MP4 video file
        episode_length: Number of frames in the episode
        fps: Frames per second

    Returns:
        Sampled frames as numpy array of shape (num_samples, channels, height, width)
        with dtype uint8
    """
    # Use the same sampling strategy as compute_stats.py
    sampled_indices = sample_indices(episode_length)

    # Convert frame indices to timestamps
    timestamps = [idx / fps for idx in sampled_indices]

    # Decode frames at the sampled timestamps
    # decode_video_frames returns torch.Tensor of shape (num_frames, C, H, W)
    # in float32 range [0, 1]. We need to convert to uint8 [0, 255] and apply downsampling
    try:
        import torch
        frames_tensor = decode_video_frames(
            video_path=video_path,
            timestamps=timestamps,
            tolerance_s=1.0 / fps,  # Allow 1 frame tolerance
        )

        # Convert to numpy: (num_frames, C, H, W) with values [0, 255]
        # decode_video_frames returns float32 in [0, 1], so multiply by 255
        frames_np = (frames_tensor.numpy() * 255).astype(np.uint8)

        # Apply downsampling to reduce memory usage (same as sample_images)
        sampled_frames = []
        for i in range(len(frames_np)):
            frame = frames_np[i]  # (C, H, W)
            frame_downsampled = auto_downsample_height_width(frame)
            sampled_frames.append(frame_downsampled)

        result = np.stack(sampled_frames, axis=0)
        logging.info(
            f"Sampled {len(sampled_indices)} frames from {video_path.name}: "
            f"shape={result.shape}, dtype={result.dtype}"
        )
        return result

    except Exception as e:
        logging.error(f"Failed to sample frames from {video_path}: {e}")
        raise


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    packet_buffer: VideoPacketBuffer | None = None,
    ffmpeg_cameras: list[str] | None = None,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(t, (so100_leader.SO100Leader, so101_leader.SO101Leader, koch_leader.KochLeader))
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # if policy is given it needs cleaning up
    if policy is not None:
        policy.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        observation = robot.get_observation()

        # Handle FFMPEGPacket cameras: read packets and buffer them
        # Note: robot.get_observation() already returned placeholder images for FFMPEGPacket cameras
        # Now we read the actual compressed packets and buffer them
        if packet_buffer is not None and ffmpeg_cameras and hasattr(robot, 'cameras'):
            from lerobot.cameras.ros2 import FFMPEGPacketCamera

            for cam_name in ffmpeg_cameras:
                if cam_name in robot.cameras and isinstance(robot.cameras[cam_name], FFMPEGPacketCamera):
                    try:
                        # Read compressed packet (not decoded!)
                        packet = robot.cameras[cam_name].read_packet(timeout_s=1.0)

                        # Buffer packet for later muxing to MP4
                        packet_buffer.add_packet(
                            camera_name=cam_name,
                            packet_data=packet.data,
                            width=packet.width,
                            height=packet.height,
                            codec=packet.codec,
                            pts=packet.pts,
                            flags=packet.flags,
                        )

                        # Keep the placeholder image in observation for dataset features validation
                        # The actual video will come from the packet buffer, not from the dataset frames

                    except Exception as e:
                        logging.warning(f"Failed to read packet from {cam_name}: {e}")

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if policy is not None:
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
        elif policy is None and isinstance(teleop, Teleoperator):
            action = teleop.get_action()
        elif policy is None and isinstance(teleop, list):
            # TODO(pepijn, steven): clean the record loop for use of multiple robots (possibly with pipeline)
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)

            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Only send action to robot if using a policy
        # When using teleop, the teleoperator is already controlling the robot directly
        if policy is not None:
            # Action can eventually be clipped using `max_relative_target`,
            # so action actually sent is saved in the dataset.
            sent_action = robot.send_action(action)
        else:
            # When using teleop, just record the action from teleoperator without sending
            sent_action = action

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}

            # Note: FFMPEGPacket camera frames are already excluded from `frame` because
            # they were filtered out from dataset.features. Their videos are handled
            # separately via packet_buffer, not through add_frame().

            dataset.add_frame(frame, task=single_task)

        if display_data:
            log_rerun_data(observation, action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    # Detect FFMPEGPacket cameras BEFORE creating dataset features
    # We need to exclude them from dataset features since we won't pass frames for them
    ffmpeg_cameras = []
    if hasattr(robot, 'cameras'):
        from lerobot.cameras.ros2 import FFMPEGPacketCamera

        ffmpeg_cameras = [
            cam_name for cam_name, cam in robot.cameras.items()
            if isinstance(cam, FFMPEGPacketCamera)
        ]

        if ffmpeg_cameras:
            logging.info(f"Detected {len(ffmpeg_cameras)} FFMPEGPacket camera(s): {ffmpeg_cameras}")
            logging.info("Using direct packet muxing (7x faster, better quality)")

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)

    # Keep FFMPEGPacket cameras in dataset features
    # Placeholder images will be saved to parquet (for video column references)
    # Actual video data comes from VideoPacketWriter direct packet muxing
    if ffmpeg_cameras:
        logging.info(f"Detected {len(ffmpeg_cameras)} FFMPEGPacket camera(s): {ffmpeg_cameras}")
        logging.info(f"Placeholder PNGs will create video column references in parquet")

    dataset_features = {**action_features, **obs_features}

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Create VideoPacketBuffer for FFMPEGPacket cameras
    # Note: We'll add video features to metadata later, right before save_episode(),
    # to avoid KeyError in add_frame()'s episode_buffer
    packet_buffer = None
    if ffmpeg_cameras:
        packet_buffer = VideoPacketBuffer(root_dir=dataset.root, fps=cfg.dataset.fps)

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()
    joy_node = init_joy_listener(events)

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            # Wait for space key or X button to start recording (skip in headless mode)
            if not is_headless() and not events["start_recording"]:
                if joy_node is not None:
                    joy_node.is_recording = False
                log_say(f"Press SPACE or X button to start recording episode {dataset.num_episodes}", cfg.play_sounds)
                logging.info("Waiting for SPACE key or X button to start recording...")
                while not events["start_recording"] and not events["stop_recording"]:
                    time.sleep(0.1)  # Small delay to avoid busy waiting
                
                # If user pressed ESC while waiting, exit
                if events["stop_recording"]:
                    break
            
            # Clear start_recording flag after entering recording
            events["start_recording"] = False
            if joy_node is not None:
                joy_node.is_recording = True
                joy_node.publish_record_trigger()
            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                policy=policy,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                packet_buffer=packet_buffer,
                ffmpeg_cameras=ffmpeg_cameras,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                events["start_recording"] = True  # 自动重新开始录制
                dataset.clear_episode_buffer()
                # Clear packet buffer too
                if packet_buffer is not None:
                    packet_buffer.clear()
                continue

            # Normal episode end - publish stop trigger
            if joy_node is not None:
                joy_node.publish_record_stop()

            # Save FFMPEGPacket videos first (if any)
            if packet_buffer is not None and ffmpeg_cameras:
                logging.info(f"Muxing {len(ffmpeg_cameras)} FFMPEGPacket video(s) to MP4...")

                # Save videos via packet buffer (direct packet muxing to MP4)
                packet_buffer.save_episode(
                    episode_index=dataset.num_episodes,
                    dataset_meta=dataset.meta
                )
                packet_buffer.clear()

                # Replace placeholder PNG paths in episode_buffer with sampled frames from MP4
                # This ensures compute_episode_stats() gets real video data instead of black PNGs
                logging.info("Sampling frames from MP4 videos for stats computation...")
                episode_length = dataset.episode_buffer["size"]

                for cam_name in ffmpeg_cameras:
                    video_key = f"observation.images.{cam_name}"

                    # Get the MP4 path (same as what we just wrote)
                    video_path = dataset.root / dataset.meta.get_video_file_path(
                        dataset.num_episodes, video_key
                    )

                    if not video_path.exists():
                        logging.warning(f"Video not found: {video_path}, skipping stats for {cam_name}")
                        continue

                    # Sample frames from MP4
                    try:
                        sampled_frames = sample_frames_from_video(
                            video_path=video_path,
                            episode_length=episode_length,
                            fps=dataset.fps
                        )

                        # Replace PNG paths with numpy array in episode_buffer
                        # compute_episode_stats() expects either:
                        # - list of image paths (for PNG) -> calls sample_images()
                        # - numpy array (for pre-sampled data) -> directly computes stats
                        dataset.episode_buffer[video_key] = sampled_frames

                        logging.info(f"Replaced {cam_name} PNG paths with {len(sampled_frames)} sampled frames")
                    except Exception as e:
                        logging.error(f"Failed to sample frames from {cam_name}: {e}")
                        # Keep the PNG paths as fallback (will result in zero stats)

            # Check if ALL cameras are FFMPEGPacket cameras
            # If so, we need to skip batch encoding logic since videos are already saved
            all_cameras_are_ffmpeg = False
            if packet_buffer is not None and ffmpeg_cameras:
                # Count total camera keys in dataset
                total_camera_keys = len([k for k in dataset.meta.video_keys if k.startswith("observation.images.")])
                all_cameras_are_ffmpeg = len(ffmpeg_cameras) == total_camera_keys
                
                if all_cameras_are_ffmpeg:
                    # All cameras use FFMPEGPacket - videos already saved via packet_buffer
                    # Force immediate "encoding" (actually skip) to avoid batch encoding assertion errors
                    original_batch_size = dataset.batch_encoding_size
                    dataset.batch_encoding_size = 1
                    logging.info(f"All {total_camera_keys} cameras use FFMPEGPacket - skipping batch encoding")

            # Save episode (this validates episode_buffer and computes stats)
            # For FFMPEGPacket cameras, stats are now computed from real MP4 frames
            # For normal cameras, stats are computed from PNG paths as usual
            dataset.save_episode()

            # Restore original batch encoding size if we modified it
            if packet_buffer is not None and ffmpeg_cameras and all_cameras_are_ffmpeg:
                dataset.batch_encoding_size = original_batch_size

            # Clean up placeholder PNG images AFTER save_episode
            # (PNG paths were already replaced with MP4 frames for stats computation,
            #  but the actual PNG files still exist on disk and need cleanup)
            if packet_buffer is not None and ffmpeg_cameras:
                import shutil
                for cam_name in ffmpeg_cameras:
                    video_key = f"observation.images.{cam_name}"
                    img_dir = dataset._get_image_file_path(
                        episode_index=dataset.num_episodes - 1,  # Episode was just saved, so num_episodes already incremented
                        image_key=video_key,
                        frame_index=0
                    ).parent
                    if img_dir.is_dir():
                        shutil.rmtree(img_dir)
                        logging.info(f"Removed placeholder PNGs: {img_dir}")

            if joy_node is not None:
                joy_node.is_recording = False
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if joy_node is not None:
        try:
            import rclpy
            joy_node.destroy_node()
            if rclpy.ok():
                rclpy.shutdown()
        except Exception as e:
            logging.warning(f"Failed to cleanup joy listener: {e}")

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    record()


if __name__ == "__main__":
    main()
